CREATE DATABASE TripPlanner;
USE TripPlanner;

-- User
CREATE TABLE [User](
Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
[Name] NVARCHAR(30) NOT NULL,
[Address] NVARCHAR(30) NOT NULL,
PhoneNumber NVARCHAR(10) NOT NULL,
DOB DATE NOT NULL
);

-- Trip
CREATE TABLE Trip(
Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
[Name] NVARCHAR(30),
Budget FLOAT NOT NULL,
StartLocation NVARCHAR(50) NOT NULL,
Destination NVARCHAR(50) NOT NULL,
TravelMode NVARCHAR(30) NOT NULL,
StartDate DATE NOT NULL,
EndDate DATE NOT NULL,
UserId INT FOREIGN KEY REFERENCES [User](Id)
);

-- Passport
CREATE TABLE Passport(
Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
PPNumber INT UNIQUE NOT NULL,
ExpDate DATE NOT NULL,
Nationality NVARCHAR(20) NOT NULL,
UserId INT UNIQUE FOREIGN KEY REFERENCES [User](Id)
);

-- Hotel
CREATE TABLE Hotel(
Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
[Name] NVARCHAR(30) NOT NULL,
[Address] NVARCHAR(30) NOT NULL,
PhoneNumber NVARCHAR(10) NOT NULL,
CheckInDate DATE NOT NULL,
CheckOutDate DATE NOT NULL,
CostPerNight FLOAT NOT NULL,
TripId INT FOREIGN KEY REFERENCES Trip(Id)
);

-- Booking
-- Serves as the "third table" present in a 
--   Many-To-Many relationship between Hotel and User
CREATE TABLE Booking(
Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
RoomNum SMALLINT UNIQUE NOT NULL,
Nights SMALLINT NOT NULL,
UserId INT FOREIGN KEY REFERENCES [User](Id),
HotelId INT FOREIGN KEY REFERENCES Hotel(Id)
);